GroceryApp/Models/Domain/Supplier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GroceryApp.Models.Domain
{
    public class Supplier
    {
        /*unique identifier for the supplier*/
        [Key]
        [Required]
        [Display(Name = "Supplier Code")]
        public string SupplierCode { get; set; }

        /*name of supplier*/
        [Required]
        [Display(Name = "Company Name")]
        public string SupplierName { get; set; }


        /*street address for supplier*/
        [Required]
        [Display(Name = "Street Address")]
        public string StreetAddress { get; set; }


        /*parish adress for supplier*/
        public int ParishID { get; set; }
        public virtual Parish Parish { get; set; }

        public virtual ICollection<Product> Products { get; set; }

        
    }
}

GroceryApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryApp.Models.Domain;
using GroceryApp.Models.Services;

namespace GroceryApp.Controllers
{ 
    public class CategoryController : Controller
    {
        private GroceryDbContext db = new GroceryDbContext();

        //
        // GET: /Category/
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            return View(db.Categories.ToList());
        }

        //
        // GET: /Category/Details/5
        [Authorize(Roles = "Admin")]
        public ViewResult Details(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        //
        // GET: /Category/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Category/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(category);
        }
        
        //
        // GET: /Category/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        //
        // POST: /Category/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /Category/Delete/5
       [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        //
        // POST: /Category/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GroceryApp/Controllers/ParishController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryApp.Models.Domain;
using GroceryApp.Models.Services;

namespace GroceryApp.Controllers
{ 
    public class ParishController : Controller
    {
        private GroceryDbContext db = new GroceryDbContext();

        //
        // GET: /Parish/
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            return View(db.Parish.ToList());
        }

        //
        // GET: /Parish/Details/5
        [Authorize(Roles = "Admin")]
        public ViewResult Details(int id)
        {
            Parish parish = db.Parish.Find(id);
            return View(parish);
        }

        //
        // GET: /Parish/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Parish/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Parish parish)
        {
            if (ModelState.IsValid)
            {
                db.Parish.Add(parish);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(parish);
        }
        
        //
        // GET: /Parish/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Parish parish = db.Parish.Find(id);
            return View(parish);
        }

        //
        // POST: /Parish/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Parish parish)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parish);
        }

        //
        // GET: /Parish/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Parish parish = db.Parish.Find(id);
            return View(parish);
        }

        //
        // POST: /Parish/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Parish parish = db.Parish.Find(id);
            db.Parish.Remove(parish);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GroceryApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryApp.Models.Domain;
using GroceryApp.Models.Services;
using GroceryApp.Models.Business;

namespace GroceryApp.Controllers
{ 
    public class ProductController : Controller
    {
        private GroceryDbContext db = new GroceryDbContext();
        private ProductMgr ProdMgr = new ProductMgr();
        //
        // GET: /Product/
         [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            var products = db.Products.Include(p => p.Category).Include(p => p.Supplier).Include(p => p.Unit);
            return View(products.ToList());
        }

        //
        // GET: /Product/Details/5
         [Authorize(Roles = "Admin")]
        public ViewResult Details(string id)
        {
            Product product = db.Products.Find(id);
            return View(product);
        }

        //
        // GET: /Product/Create
         [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "name");
            ViewBag.SupplierCode = new SelectList(db.Suppliers, "SupplierCode", "SupplierName");
            ViewBag.UnitID = new SelectList(db.Units, "UnitID", "name");
            return View();
        } 

        //
        // POST: /Product/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
               // db.Products.Add(product);
                //db.SaveChanges();
                ProdMgr.AddProduct(product);
                return RedirectToAction("Index");  
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "name", product.CategoryID);
            ViewBag.SupplierCode = new SelectList(db.Suppliers, "SupplierCode", "SupplierName", product.SupplierCode);
            ViewBag.UnitID = new SelectList(db.Units, "UnitID", "name", product.UnitID);
            return View(product);
        }
        
        //
        // GET: /Product/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
           // Product product = db.Products.Find(id);
            Product product = ProdMgr.SearchProduct(id);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "name", product.CategoryID);
            ViewBag.SupplierCode = new SelectList(db.Suppliers, "SupplierCode", "SupplierName", product.SupplierCode);
            ViewBag.UnitID = new SelectList(db.Units, "UnitID", "name", product.UnitID);
            return View(product);
        }

        //
        // POST: /Product/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(product).State = EntityState.Modified;
               // db.SaveChanges();
                ProdMgr.UpdateProduct(product);
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "name", product.CategoryID);
            ViewBag.SupplierCode = new SelectList(db.Suppliers, "SupplierCode", "SupplierName", product.SupplierCode);
            ViewBag.UnitID = new SelectList(db.Units, "UnitID", "name", product.UnitID);
            return View(product);
        }

        //
        // GET: /Product/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            Product product = db.Products.Find(id);
            return View(product);
        }

        //
        // POST: /Product/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {            
           // Product product = db.Products.Find(id);
           // db.Products.Remove(product);
           // db.SaveChanges();
            ProdMgr.RemoveProduct(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GroceryApp/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryApp.Models.Domain;
using GroceryApp.Models.Services;
using GroceryApp.Models.Business;

namespace GroceryApp.Controllers
{ 
    public class SupplierController : Controller
    {
        private GroceryDbContext db = new GroceryDbContext();
        private SupplierMgr SuppMgr = new SupplierMgr();

        //
        // GET: /Supplier/
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            var suppliers = db.Suppliers.Include(s => s.Parish);
            return View(suppliers.ToList());
        }

        //
        // GET: /Supplier/Details/5
        [Authorize(Roles = "Admin")]
        public ViewResult Details(string id)
        {
            Supplier supplier = SuppMgr.SearchSupplier(id);
           // Supplier supplier = db.Suppliers.Find(id);
            return View(supplier);
        }

        //
        // GET: /Supplier/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ParishID = new SelectList(db.Parish, "ParishID", "name");
            return View();
        } 

        //
        // POST: /Supplier/Create
       [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                //db.Suppliers.Add(supplier);
                //db.SaveChanges();
                SuppMgr.AddSupplier(supplier);
                return RedirectToAction("Index");  
            }

            ViewBag.ParishID = new SelectList(db.Parish, "ParishID", "name", supplier.ParishID);
            return View(supplier);
        }
        
        //
        // GET: /Supplier/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
           // Supplier supplier = db.Suppliers.Find(id);
            Supplier supplier = SuppMgr.SearchSupplier(id);
            ViewBag.ParishID = new SelectList(db.Parish, "ParishID", "name", supplier.ParishID);
            return View(supplier);
        }

        //
        // POST: /Supplier/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(supplier).State = EntityState.Modified;
               // db.SaveChanges();
                SuppMgr.UpdateSupplier(supplier);
                return RedirectToAction("Index");
            }
            ViewBag.ParishID = new SelectList(db.Parish, "ParishID", "name", supplier.ParishID);
            return View(supplier);
        }

        //
        // GET: /Supplier/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            Supplier supplier = db.Suppliers.Find(id);
            return View(supplier);
        }

        //
        // POST: /Supplier/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {            
            //Supplier supplier = db.Suppliers.Find(id);
            //db.Suppliers.Remove(supplier);
          //  db.SaveChanges();
            SuppMgr.RemoveSupplier(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GroceryApp/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GroceryApp.Models.Domain;
using GroceryApp.Models.Services;

namespace GroceryApp.Controllers
{ 
    public class UnitController : Controller
    {
        private GroceryDbContext db = new GroceryDbContext();

        //
        // GET: /Unit/
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            return View(db.Units.ToList());
        }

        //
        // GET: /Unit/Details/5
        [Authorize(Roles = "Admin")]
        public ViewResult Details(int id)
        {
            Unit unit = db.Units.Find(id);
            return View(unit);
        }

        //
        // GET: /Unit/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Unit/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Units.Add(unit);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(unit);
        }
        
        //
        // GET: /Unit/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Unit unit = db.Units.Find(id);
            return View(unit);
        }

        //
        // POST: /Unit/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Unit unit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(unit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(unit);
        }

        //
        // GET: /Unit/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Unit unit = db.Units.Find(id);
            return View(unit);
        }

        //
        // POST: /Unit/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Unit unit = db.Units.Find(id);
            db.Units.Remove(unit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GroceryApp/Views/Supplier/Create.cshtml
@model GroceryApp.Models.Domain.Supplier

@{
    ViewBag.Title = "Create";
    Layout = "~/views/shared/_layout.cshtml";
}
<div id="title">
                <h1>Sharon's Grocery Store</h1>
             <strong> Number of Visits : @HttpContext.Current.Application["Visits"] </strong> |
             <strong> Your IP Address is : @Session["IPAddress"].ToString() </strong> |  @Html.Partial("_LogOnPartial") 
           
                
            </div>

             
               
            

 <div id="menucontainer">

                
                 <strong> @Html.ActionLink("Home", "Index", "Home") </strong> |
                 <strong> @Html.ActionLink("About", "About", "Home") </strong> |
                 <strong> @Html.ActionLink("Products", "Index", "Product") </strong> |
                 <strong> @Html.ActionLink("Suppliers", "Index", "Supplier")</strong> |
                 <strong> @Html.ActionLink("Categories", "Index", "Category") </strong> |
                 <strong>@Html.ActionLink("Parishes", "Index", "Parish") </strong> |
                  <strong>@Html.ActionLink("Units", "Index", "Unit") </strong> |
                    
            </div>

<h2>Create</h2>
<strong> Hi user from: @Session["IPAddress"].ToString() , this menu is used for adding suppliers.</strong>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Supplier</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SupplierCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SupplierCode)
            @Html.ValidationMessageFor(model => model.SupplierCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SupplierName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SupplierName)
            @Html.ValidationMessageFor(model => model.SupplierName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StreetAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StreetAddress)
            @Html.ValidationMessageFor(model => model.StreetAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParishID, "Parish")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ParishID", String.Empty)
            @Html.ValidationMessageFor(model => model.ParishID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroceryApp/Views/Supplier/Delete.cshtml
@model GroceryApp.Models.Domain.Supplier

@{
    ViewBag.Title = "Delete";
    Layout = "~/views/shared/_layout.cshtml";
}
<div id="title">
                <h1>Sharon's Grocery Store</h1>
             <strong> Number of Visits : @HttpContext.Current.Application["Visits"] </strong> |
             <strong> Your IP Address is : @Session["IPAddress"].ToString() </strong> |  @Html.Partial("_LogOnPartial") 
           
                
            </div>

             
               
            

 <div id="menucontainer">

                
                 <strong> @Html.ActionLink("Home", "Index", "Home") </strong> |
                 <strong> @Html.ActionLink("About", "About", "Home") </strong> |
                 <strong> @Html.ActionLink("Products", "Index", "Product") </strong> |
                 <strong> @Html.ActionLink("Suppliers", "Index", "Supplier")</strong> |
                 <strong> @Html.ActionLink("Categories", "Index", "Category") </strong> |
                 <strong>@Html.ActionLink("Parishes", "Index", "Parish") </strong> |
                  <strong>@Html.ActionLink("Units", "Index", "Unit") </strong> |
                    
            </div>

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">SupplierName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SupplierName)
    </div>

    <div class="display-label">StreetAddress</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StreetAddress)
    </div>

    <div class="display-label">Parish</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Parish.name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

GroceryApp/Views/Supplier/Details.cshtml
@model GroceryApp.Models.Domain.Supplier

@{
    ViewBag.Title = "Details";
    Layout = "~/views/shared/_layout.cshtml";
}
<div id="title">
                <h1>Sharon's Grocery Store</h1>
             <strong> Number of Visits : @HttpContext.Current.Application["Visits"] </strong> |
             <strong> Your IP Address is : @Session["IPAddress"].ToString() </strong> |  @Html.Partial("_LogOnPartial") 
           
                
            </div>

             
               
            

 <div id="menucontainer">

                
                 <strong> @Html.ActionLink("Home", "Index", "Home") </strong> |
                 <strong> @Html.ActionLink("About", "About", "Home") </strong> |
                 <strong> @Html.ActionLink("Products", "Index", "Product") </strong> |
                 <strong> @Html.ActionLink("Suppliers", "Index", "Supplier")</strong> |
                 <strong> @Html.ActionLink("Categories", "Index", "Category") </strong> |
                 <strong>@Html.ActionLink("Parishes", "Index", "Parish") </strong> |
                  <strong>@Html.ActionLink("Units", "Index", "Unit") </strong> |
                    
            </div>

<h2>Details</h2>

<fieldset>
    <legend>Supplier</legend>

     <div class="display-label">SupplierCode</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SupplierCode)
    </div>

    <div class="display-label">SupplierName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SupplierName)
    </div>

    <div class="display-label">StreetAddress</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StreetAddress)
    </div>

    <div class="display-label">Parish</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Parish.name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.SupplierCode }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GroceryApp/Views/Supplier/Edit.cshtml
@model GroceryApp.Models.Domain.Supplier

@{
    ViewBag.Title = "Edit";
    Layout = "~/views/shared/_layout.cshtml";
}
<div id="title">
                <h1>Sharon's Grocery Store</h1>
             <strong> Number of Visits : @HttpContext.Current.Application["Visits"] </strong> |
             <strong> Your IP Address is : @Session["IPAddress"].ToString() </strong> |  @Html.Partial("_LogOnPartial") 
           
                
            </div>

             
               
            

 <div id="menucontainer">

                
                 <strong> @Html.ActionLink("Home", "Index", "Home") </strong> |
                 <strong> @Html.ActionLink("About", "About", "Home") </strong> |
                 <strong> @Html.ActionLink("Products", "Index", "Product") </strong> |
                 <strong> @Html.ActionLink("Suppliers", "Index", "Supplier")</strong> |
                 <strong> @Html.ActionLink("Categories", "Index", "Category") </strong> |
                 <strong>@Html.ActionLink("Parishes", "Index", "Parish") </strong> |
                  <strong>@Html.ActionLink("Units", "Index", "Unit") </strong> |
                    
            </div>
<h2>Edit</h2>
<strong> Hi user from: @Session["IPAddress"].ToString() , this menu is used for updating suppliers.</strong>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Supplier</legend>

        @Html.HiddenFor(model => model.SupplierCode)

        <div class="editor-label">
            @Html.LabelFor(model => model.SupplierName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SupplierName)
            @Html.ValidationMessageFor(model => model.SupplierName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StreetAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StreetAddress)
            @Html.ValidationMessageFor(model => model.StreetAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParishID, "Parish")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ParishID", String.Empty)
            @Html.ValidationMessageFor(model => model.ParishID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroceryApp/Views/Supplier/Index.cshtml
@model IEnumerable<GroceryApp.Models.Domain.Supplier>

@{
    ViewBag.Title = "Index";
    Layout = "~/views/shared/_layout.cshtml";
}
<div id="title">
                <h1>Sharon's Grocery Store</h1>
             <strong> Number of Visits : @HttpContext.Current.Application["Visits"] </strong> |
             <strong> Your IP Address is : @Session["IPAddress"].ToString() </strong> |  @Html.Partial("_LogOnPartial") 
           
                
            </div>

             
               
            

 <div id="menucontainer">

                
                 <strong> @Html.ActionLink("Home", "Index", "Home") </strong> |
                 <strong> @Html.ActionLink("About", "About", "Home") </strong> |
                 <strong> @Html.ActionLink("Products", "Index", "Product") </strong> |
                 <strong> @Html.ActionLink("Suppliers", "Index", "Supplier")</strong> |
                 <strong> @Html.ActionLink("Categories", "Index", "Category") </strong> |
                 <strong>@Html.ActionLink("Parishes", "Index", "Parish") </strong> |
                  <strong>@Html.ActionLink("Units", "Index", "Unit") </strong> |
                    
            </div>
<h2>Supplier Management</h2>
<strong> Hi user from: @Session["IPAddress"].ToString() , this menu is used for Supplier management.</strong>

<p>
    @Html.ActionLink("Create New Supplier", "Create")
</p>
<table>
    <tr>
        <th>
            SupplierName
        </th>
        <th>
            StreetAddress
        </th>
        <th>
            Parish
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SupplierName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StreetAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Parish.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SupplierCode }) |
            @Html.ActionLink("Details", "Details", new { id=item.SupplierCode }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SupplierCode })
        </td>
    </tr>
}

</table>